import type { Metadata } from 'next'
import './globals.css'
import Sidebar from './components/Sidebar/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-color flex min-h-screen relative gap-8'>
        <Sidebar/>
        {children}
      </body>
    </html>
  )
}
